export const episodios = [
    {
        numero: 1,
        url: "https://drive.google.com/file/d/1g2Dbt7GgXzSZx0W9b093qUEy0jhXyaqm/view?usp=sharing",
        titulo: 'Aquí Está Ranma',
        miniatura: 'https://i.ibb.co/VWf8RZk9/miniatura-q.jpg',
        temporada: 1,
    },
    {
        numero: 2,
        url: "https://drive.google.com/file/d/1lMUQntwmoYqTXNxHlVVjTRfl9l0k6HAN/view?usp=sharing",
        titulo: '¡Odio a los hombres!',
        miniatura: 'https://i.ibb.co/35yH891n/2.jpg',
        temporada: 1,
    },
    {
        numero: 3,
        url: "https://drive.google.com/file/d/1aEwL0wSoxdTfsMYIXsqvjFgMdj_gJnuG/view?usp=sharing",
        titulo: 'Porque le gusta alguien',
        miniatura: 'https://i.ibb.co/XkSp3XpL/3.jpg',
        temporada: 1,
    },
    {
        numero: 4,
        url: "https://drive.google.com/file/d/1Af24FUK_a3Xf8Yd561ongY_AKodz6JaI/view?usp=sharing",
        titulo: 'El hombre que perseguía a Ranma',
        miniatura: 'https://i.ibb.co/N6ssXKDY/4.jpg',
        temporada: 1,
    },
    {
        numero: 5,
        url: "https://drive.google.com/file/d/1f88DgNbefyWLa05Wy30I3Pu3KC3S9_4P/view?usp=sharing",
        titulo: 'Eres odiosa',
        miniatura: 'https://i.ibb.co/32SJXQJ/5.jpg',
        temporada: 1,
    },
    {
        numero: 6,
        url: "https://drive.google.com/file/d/1DJQDI0JCKGhwqNP0rsZKAobIn76lLLD6/view?usp=sharing",
        titulo: 'Kodachi de la rosa negra',
        miniatura: 'https://i.ibb.co/TBDgv6FL/6.jpg',
        temporada: 1,
    },
    {
        numero: 7,
        url: "https://drive.google.com/file/d/1OKZE3aO2g56CUMHMCHm2XmTyvIjoh5x6/view?usp=sharing",
        titulo: 'Una disputada lucha gimnástica',
        miniatura: 'https://i.ibb.co/qT7Rk4Y/7.jpg',
        temporada: 1,
    },
    {
        numero: 8,
        url: "https://drive.google.com/file/d/1VLPAcwrlnxHMAm6b24eUqmhshtp8Er04/view?usp=sharing",
        titulo: 'Mi querido Charlotte',
        miniatura: 'https://i.ibb.co/Qw8k29P/8.jpg',
        temporada: 1,
    },
    {
        numero: 9,
        url: "https://drive.google.com/file/d/19J9dxoazGsa8OzuF7gGyDy55UYCpxug9/view?usp=sharing",
        titulo: 'Jamás te soltaré',
        miniatura: 'https://i.ibb.co/395q20GP/9.jpg',
        temporada: 1,
    },
    {
        numero: 10,
        url: "https://drive.google.com/file/d/1BwTkR8XNa2glmSGbIP_0dAnV1qmuUQDT/view?usp=sharing",
        titulo: 'El beso de la muerte',
        miniatura: 'https://i.ibb.co/LdcW7Jzd/10.jpg',
        temporada: 1,
    },
    {
        numero: 11,
        url: "https://drive.google.com/file/d/19uHJ3YGX6XNfTpHnCrGyfab3FO8dpDxS/view?usp=sharing",
        titulo: 'Wo ai ni',
        miniatura: 'https://i.ibb.co/8nCh5d7P/11.jpg',
        temporada: 1,
    },
    {
        numero: 12,
        url: "https://drive.google.com/file/d/1CsGYIRoLEJwgBIBx0w-2wW7pEpmV9co1/view?usp=sharing",
        titulo: 'El champú amnésico',
        miniatura: 'https://i.ibb.co/cKV4W6dS/1.jpg',
        temporada: 1,
    },
    {
        numero: 1,
        url: "https://drive.google.com/file/d/1tGtXoYVWXJRMUqlvjfHXO-60dHtNeUrM/view?usp=sharing",
        titulo: 'El punto debil de ranma',
        miniatura: 'https://i.ibb.co/27p1Vzkx/1.png',
        temporada: 2,
    },
    {
        numero: 2,
        url: "https://drive.google.com/file/d/1qTx2RRf0TXZPdAFHbK9DKosAj3olaHgX/view?usp=sharing",
        titulo: 'El ataque de Mousse',
        miniatura: 'https://i.ibb.co/xK5ZFnR8/2.png',
        temporada: 2,
    },
    {
        numero: 3,
        url: "https://drive.google.com/file/d/1XywFXI9lkGsdlHk5UgA8aHcAqoqXMyyG/view?usp=sharing",
        titulo: 'Técnica de las castañas dulces asadas',
        miniatura: 'https://i.ibb.co/fVfBB6MF/3.png',
        temporada: 2,
    },
    {
        numero: 4,
        url: "https://drive.google.com/file/d/1BBjDXJ_2JawoH1j-4-rtbUYI9qF5VAoW/view?usp=sharing",
        titulo: 'Batalla naval',
        miniatura: 'https://i.ibb.co/6cj4r6gk/4.png',
        temporada: 2,
    },
    {
        numero: 5,
        url: "https://drive.google.com/file/d/1FRpTdiuv4UV0QyTChmODcOAummwvnbz8/view?usp=sharing",
        titulo: 'Lucha de repartidoras',
        miniatura: 'https://i.ibb.co/V0FBnX1N/5.png',
        temporada: 2,
    },
    {
        numero: 6,
        url: "https://drive.google.com/file/d/1YhglRF2LQUqRGK4nMyTFwVpVGJMf90z8/view?usp=sharing",
        titulo: 'Renace el mal absoluto',
        miniatura: 'https://i.ibb.co/rGXw5W2R/6.png',
        temporada: 2,
    },
    {
        numero: 7,
        url: "https://drive.google.com/file/d/15H9QaLawiwLvm1NfiOIojpM9ifNF853F/view?usp=drive_link",
        titulo: 'Las sales del estanque del hommbre ahogado',
        miniatura: 'https://i.ibb.co/r2RjZf2C/7.png',
        temporada: 2,
    },
    {
        numero: 8,
        url: "https://drive.google.com/file/d/12eYyarCnMLm5jrBrQjy0U_bdHPcHZlph/view?usp=drive_link",
        titulo: 'Ukyo de los Okonomiyaki',
        miniatura: 'https://i.ibb.co/39XLYvPn/8.png',
        temporada: 2,
    },
    {
        numero: 9,
        url: "https://drive.google.com/file/d/1t4ooefCEDckbQfOCESerao5eUESTPfvc/view",
        titulo: 'Una carta de amor perfecta',
        miniatura: 'https://i.ibb.co/8LL7KdCj/9.png',
        temporada: 2,
    },
    {
        numero: 10,
        url: "https://drive.google.com/file/d/1DFyrqqxkWnjWhUDj1dNcIl_Bd3vjdkcq/view",
        titulo: 'Jugando a ser Julieta',
        miniatura: 'https://i.ibb.co/HTYK3XrB/10.png',
        temporada: 2,
    },
    {
        numero: 11,
        url: "https://drive.google.com/file/d/1-MODTC-a8hwNVOdPUs3Nq8DlHMMPs5rC/view",
        titulo: 'El rapto de akane',
        miniatura: 'https://i.ibb.co/7JJ3zvvP/11.png',
        temporada: 2,
    },
    {
        numero: 12,
        url: "https://drive.google.com/file/d/1JTGtJdQZHkiXcEwg5dSTqUKoPXKx13kT/view",
        titulo: 'Animo, Mousse',
        miniatura: 'https://i.ibb.co/NdB2VRNc/12.png',
        temporada: 2,
    },
    
    
   
]